spring:
  profiles:
    active: db
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      database: h2
      mode: always
  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect