server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8083/
          predicates:
            - Path=/product/**
        - id: inventory-service
          uri: http://localhost:8082/
          predicates:
            - Path=/inventory/**
        - id: catalog-service
          uri: http://localhost:8081/
          predicates:
            - Path=/catalog/**
