server:
  port: 8086

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://192.168.0.103:8083/
          predicates:
            - Path=/product/**
        - id: inventory-service
          uri: http://192.168.0.103:8082/
          predicates:
            - Path=/inventory/**
        - id: catalog-service
          uri: http://192.168.0.103:8081/
          predicates:
            - Path=/catalog/**
management:
  endpoints:
    web:
      exposure:
        include: "*"