server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: productService
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
        - id: inventoryService
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
        - id: catalogService
          uri: http://localhost:8081
          predicates:
            - Path=/catalog/**
